# Generated by Django 4.1.5 on 2023-02-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_comment_recommend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book',
            new_name='post',
        ),
    ]
